name: Build Kivy Android App

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip build-essential libssl-dev libffi-dev python3-dev \
                            liblzma-dev libsqlite3-dev libgdbm-dev libbz2-dev \
                            zlib1g-dev libreadline-dev libffi-dev libffi8 libgdbm-compat-dev \
                            openjdk-11-jdk unzip curl tar
        pip install --upgrade pip setuptools cython buildozer

    - name: Generate buildozer.spec
      run: |
        echo "[app]" > buildozer.spec
        echo "title = MyApp" >> buildozer.spec
        echo "package.name = myapp" >> buildozer.spec
        echo "package.domain = org.example" >> buildozer.spec
        echo "source.dir = ." >> buildozer.spec
        echo "source.include_exts = py,kv,json" >> buildozer.spec
        echo "version = 1.0.0" >> buildozer.spec
        echo "requirements = kivy" >> buildozer.spec
        echo "android.api = 29" >> buildozer.spec
        echo "android.minapi = 21" >> buildozer.spec
        echo "orientation = portrait" >> buildozer.spec

    - name: Download and Verify NDK
      run: |
        mkdir -p ~/.buildozer/android/platform
        cd ~/.buildozer/android/platform

        # Download NDK with retries
        for i in {1..3}; do
          curl -L -o ndk.zip https://github.com/android/ndk/releases/download/r21e/android-ndk-r21e-linux-x86_64.zip && break || sleep 5
        done

        # Validate SHA256 checksum
        echo "dbcf9c536482b0f3997dfb8424d34866548c0249e47a4cd8c9243fc49a2205a3  ndk.zip" | sha256sum -c -

        # If checksum fails, exit
        if [ $? -ne 0 ]; then
          echo "NDK ZIP file checksum validation failed."
          exit 1
        fi

        # Extract the NDK
        unzip ndk.zip
        mv android-ndk-r21e ~/.buildozer/android/platform/android-ndk-r21e

    - name: Set Up Buildozer Environment for the app
      run: |
        mkdir -p ~/.buildozer/android/platform/android-sdk
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d ~/.buildozer/android/platform/android-sdk/
        mv ~/.buildozer/android/platform/android-sdk/cmdline-tools ~/.buildozer/android/platform/android-sdk/cmdline-tools-tools
        mkdir ~/.buildozer/android/platform/android-sdk/cmdline-tools
        mv ~/.buildozer/android/platform/android-sdk/cmdline-tools-tools ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest
        yes | ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" "platforms;android-29" "build-tools;30.0.3"

    - name: Build APK
      run: buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: bin/*.apk
