name: Build Kivy Android App

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip build-essential libssl-dev libffi-dev python3-dev \
                            liblzma-dev libsqlite3-dev libgdbm-dev libbz2-dev \
                            zlib1g-dev libreadline-dev libffi-dev libffi8 libgdbm-compat-dev \
                            openjdk-11-jdk unzip
        pip install --upgrade pip setuptools cython buildozer

    - name: Set Up Buildozer Environment
      run: |
        buildozer android clean
        mkdir -p ~/.buildozer/android/platform/android-sdk
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d ~/.buildozer/android/platform/android-sdk/
        mv ~/.buildozer/android/platform/android-sdk/cmdline-tools ~/.buildozer/android/platform/android-sdk/cmdline-tools-tools
        mkdir ~/.buildozer/android/platform/android-sdk/cmdline-tools
        mv ~/.buildozer/android/platform/android-sdk/cmdline-tools-tools ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest
        yes | ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" "platforms;android-29" "build-tools;30.0.3" "ndk;21.4.7075529"

    - name: Build APK
      run: buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: bin/*.apk
